name: Build and Release DMG

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Install dependencies
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Decode and install certificate
        run: |
          echo "${{ secrets.MACOS_CERTIFICATE }}" | base64 --decode > cert.p12
          security create-keychain -p "" build.keychain
          security import cert.p12 -k ~/Library/Keychains/build.keychain -P "${{ secrets.MACOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain

      - name: Build project
        run: xcodebuild -project AudioSwitcher.xcodeproj -scheme AudioSwitcher -configuration Release build CODE_SIGN_IDENTITY="Apple Development"

      - name: Create DMG
        run: |
          mkdir -p build/Release
          hdiutil create -volname AudioSwitcher -srcfolder build/Release -ov -format UDZO build/Release/AudioSwitcher.dmg

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.ref }}
          name: Release v${{ github.ref }}
          files: build/Release/AudioSwitcher.dmg
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.AUDIOSWITCHER_PAT }}
